{% set name = "sqlalchemy-stubs" %}
{% set version = "0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-stubs-{{ version }}.tar.gz
  sha256: c665d6dd4482ef642f01027fa06c3d5e91befabb219dc71fc2a09e7d7695f7ae

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - mypy >=0.790
    - python >={{ python_min }}
    - typing-extensions >=3.7.4

test:
  # Import test is done in run_test.py due to - character in package name.
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dropbox/sqlalchemy-stubs
  summary: SQLAlchemy stubs and mypy plugin
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
